### ISSUE TITLE
Cannot find module 'ERC20Contract'

### ISSUE THREAD

**Issue by Vulturio** [OsoianMarcel/erc20-contract-js#1]
Cannot find module 'ERC20Contract'

**Comment by OsoianMarcel** [comment]
Hi,

Please add more details about your problem and I'll try to reproduce the problem (nodejs version, npm/yarn version, package.json, your source code).
I will try to help or fix the bug (if it exists).
P.S. We already use this library on our back-end and front-end projects.

**Comment by OsoianMarcel** [comment]
Cannot reproduce
