### ISSUE TITLE
Transfer token

### ISSUE THREAD

**Issue by lvtlover** [OsoianMarcel/erc20-contract-js#3]
Where to set private key in order to transfer token to different address?

**Comment by OsoianMarcel** [comment]
This library is a wrapper library for `web3.eth.Contract` dedicated for ERC20 (abi) contracts. It does not handle tx signatures.
1. Simpliest way is to use web3 provider from MetaMask, and `Metamask` will sign tx for you.
2. Another simple way is to import your account to `private geth node`, then to unlock your account and let geth server to sign your tx.
3. Also, you can `sign tx by yourself` by using private key (google it).

**Comment by OsoianMarcel** [comment]
I hope this will help you.
